"""initial production schema

Revision ID: bfd7cd1209eb
Revises:
Create Date: 2026-08-07 11:20:22.860440
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "bfd7cd1209eb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The migration/login owner remains separate from this deliberately unprivileged web role.
    # Production may pre-create it as LOGIN with a secret; this block is safe in development.
    op.execute(
        """
        DO $role$
        BEGIN
            CREATE ROLE kanoon_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
                NOINHERIT NOBYPASSRLS;
        EXCEPTION WHEN duplicate_object THEN
            IF EXISTS (
                SELECT 1 FROM pg_roles
                WHERE rolname = 'kanoon_app' AND (rolsuper OR rolbypassrls)
            ) THEN
                RAISE EXCEPTION 'kanoon_app must not be SUPERUSER or BYPASSRLS';
            END IF;
        END
        $role$;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authentication_attempts",
        sa.Column("scope_hash", sa.String(length=64), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authentication_attempts")),
    )
    op.create_index(
        "ix_auth_attempt_scope_created",
        "authentication_attempts",
        ["scope_hash", "created_at"],
        unique=False,
    )
    op.create_table(
        "school_directory_entries",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("city", sa.String(length=150), nullable=True),
        sa.Column("province", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school_directory_entries")),
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("default_locale", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("default_currency", sa.String(length=8), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_events",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_audit_events_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_audit_events_tenant_id_id")),
    )
    op.create_index(
        "ix_audit_events_tenant_created", "audit_events", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_tenant_entity",
        "audit_events",
        ["tenant_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_table(
        "contact_requests",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("education_level", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=False),
        sa.Column("request_ip_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handled_by", sa.Uuid(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('NEW', 'CONTACTED', 'CLOSED', 'SPAM')",
            name=op.f("ck_contact_requests_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["handled_by"], ["users.id"], name=op.f("fk_contact_requests_handled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_contact_requests_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_requests")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_contact_requests_tenant_id_id")),
    )
    op.create_index(
        "ix_contact_requests_tenant_status_created",
        "contact_requests",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_contact_requests_tenant_ip_created",
        "contact_requests",
        ["tenant_id", "request_ip_hash", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_contact_requests_tenant_phone_created",
        "contact_requests",
        ["tenant_id", "phone_number", "created_at"],
        unique=False,
    )
    op.create_table(
        "exam_offerings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("registration_starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registration_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exam_starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exam_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue_name", sa.String(length=300), nullable=True),
        sa.Column("venue_address", sa.Text(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('ONLINE', 'ONSITE')", name=op.f("ck_exam_offerings_valid_mode")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'COMPLETED', 'ARCHIVED')",
            name=op.f("ck_exam_offerings_valid_status"),
        ),
        sa.CheckConstraint(
            "capacity IS NULL OR capacity > 0", name=op.f("ck_exam_offerings_capacity_positive")
        ),
        sa.CheckConstraint(
            "exam_ends_at IS NULL OR exam_starts_at IS NULL OR exam_ends_at > exam_starts_at",
            name=op.f("ck_exam_offerings_valid_exam_window"),
        ),
        sa.CheckConstraint(
            "registration_ends_at IS NULL OR registration_starts_at IS NULL OR registration_ends_at > registration_starts_at",
            name=op.f("ck_exam_offerings_valid_registration_window"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_exam_offerings_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exam_offerings")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_exam_offerings_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_exam_offerings_tenant_id_slug")),
    )
    op.create_index(
        "ix_exam_offerings_tenant_public",
        "exam_offerings",
        ["tenant_id", "status", "registration_starts_at"],
        unique=False,
    )
    op.create_table(
        "honor_categories",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_honor_categories_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_honor_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_honor_categories_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_honor_categories_tenant_id_slug")),
    )
    op.create_table(
        "media_assets",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'READY', 'REJECTED')", name=op.f("ck_media_assets_valid_status")
        ),
        sa.CheckConstraint(
            "visibility IN ('PUBLIC', 'PRIVATE')",
            name=op.f("ck_media_assets_valid_visibility"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_media_assets_size_nonnegative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_media_assets_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_media_assets_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id", "object_key", name=op.f("uq_media_assets_tenant_id_object_key")
        ),
    )
    op.create_index(
        "ix_media_assets_tenant_created", "media_assets", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "pricing_plans",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('ONLINE', 'ONSITE')", name=op.f("ck_pricing_plans_valid_mode")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')",
            name=op.f("ck_pricing_plans_valid_status"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_pricing_plans_amount_nonnegative")),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_pricing_plans_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_plans")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_pricing_plans_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_pricing_plans_tenant_id_slug")),
    )
    op.create_index(
        "ix_pricing_plans_tenant_public",
        "pricing_plans",
        ["tenant_id", "status", "sort_order"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_refresh_tokens_tenant_id_tenants")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id", "revoked_at"], unique=False
    )
    op.create_table(
        "registration_form_definitions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_registration_form_definitions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_registration_form_definitions_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_form_definitions")),
        sa.UniqueConstraint(
            "tenant_id", "id", name=op.f("uq_registration_form_definitions_tenant_id_id")
        ),
        sa.UniqueConstraint(
            "tenant_id", "version", name=op.f("uq_registration_form_definitions_tenant_id_version")
        ),
    )
    op.create_table(
        "tenant_addresses",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("latitude", sa.String(length=32), nullable=True),
        sa.Column("longitude", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tenant_addresses_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_addresses")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tenant_addresses_tenant_id_id")),
    )
    op.create_table(
        "tenant_domains",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=253), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_domains_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_domains")),
        sa.UniqueConstraint("hostname", name=op.f("uq_tenant_domains_hostname")),
    )
    op.create_index(
        op.f("ix_tenant_domains_tenant_id"), "tenant_domains", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenant_features",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("feature_key", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_features_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "feature_key", name=op.f("pk_tenant_features")),
        sa.UniqueConstraint(
            "tenant_id", "feature_key", name=op.f("uq_tenant_features_tenant_id_feature_key")
        ),
    )
    op.create_index(
        "ix_tenant_features_tenant_enabled",
        "tenant_features",
        ["tenant_id", "enabled"],
        unique=False,
    )
    op.create_table(
        "tenant_memberships",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_memberships_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tenant_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "user_id", name=op.f("pk_tenant_memberships")),
        sa.UniqueConstraint(
            "tenant_id", "user_id", name=op.f("uq_tenant_memberships_tenant_id_user_id")
        ),
    )
    op.create_index(
        "ix_tenant_memberships_tenant_role",
        "tenant_memberships",
        ["tenant_id", "role"],
        unique=False,
    )
    op.create_table(
        "tenant_phones",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tenant_phones_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_phones")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tenant_phones_tenant_id_id")),
    )
    op.create_table(
        "tenant_profiles",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_tenant_profiles_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_profiles")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tenant_profiles_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", name=op.f("uq_tenant_profiles_tenant_id")),
    )
    op.create_table(
        "tenant_social_links",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_tenant_social_links_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant_social_links")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_tenant_social_links_tenant_id_id")),
    )
    op.create_table(
        "banners",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_id", sa.Uuid(), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f("ck_banners_valid_status")
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at",
            name=op.f("ck_banners_valid_window"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "image_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_banners_tenant_id_image_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_banners_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_banners")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_banners_tenant_id_id")),
    )
    op.create_index(
        "ix_banners_tenant_public", "banners", ["tenant_id", "status", "sort_order"], unique=False
    )
    op.create_table(
        "exam_pricing_plans",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("exam_offering_id", sa.Uuid(), nullable=False),
        sa.Column("pricing_plan_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "exam_offering_id"],
            ["exam_offerings.tenant_id", "exam_offerings.id"],
            name=op.f("fk_exam_pricing_plans_tenant_id_exam_offering_id_exam_offerings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "pricing_plan_id"],
            ["pricing_plans.tenant_id", "pricing_plans.id"],
            name=op.f("fk_exam_pricing_plans_tenant_id_pricing_plan_id_pricing_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_exam_pricing_plans_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint(
            "tenant_id", "exam_offering_id", "pricing_plan_id", name=op.f("pk_exam_pricing_plans")
        ),
    )
    op.create_table(
        "gallery_albums",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_image_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')",
            name=op.f("ck_gallery_albums_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cover_image_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_gallery_albums_tenant_id_cover_image_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_gallery_albums_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gallery_albums")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_gallery_albums_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "slug", name=op.f("uq_gallery_albums_tenant_id_slug")),
    )
    op.create_index(
        "ix_gallery_albums_tenant_public",
        "gallery_albums",
        ["tenant_id", "status", "sort_order"],
        unique=False,
    )
    op.create_table(
        "honors",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("student_name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("institution_name", sa.String(length=300), nullable=True),
        sa.Column("field_of_study", sa.String(length=200), nullable=True),
        sa.Column("image_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f("ck_honors_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["honor_categories.tenant_id", "honor_categories.id"],
            name=op.f("fk_honors_tenant_id_category_id_honor_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "image_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_honors_tenant_id_image_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_honors_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_honors")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_honors_tenant_id_id")),
    )
    op.create_index(
        "ix_honors_tenant_public", "honors", ["tenant_id", "status", "sort_order"], unique=False
    )
    op.create_table(
        "posts",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("cover_image_id", sa.Uuid(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('NEWS', 'ANNOUNCEMENT', 'BLOG')", name=op.f("ck_posts_valid_kind")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')", name=op.f("ck_posts_valid_status")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cover_image_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_posts_tenant_id_cover_image_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_posts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_posts_tenant_id_id")),
        sa.UniqueConstraint("tenant_id", "kind", "slug", name=op.f("uq_posts_tenant_id_kind_slug")),
    )
    op.create_index(
        "ix_posts_tenant_kind_public",
        "posts",
        ["tenant_id", "kind", "status", "published_at"],
        unique=False,
    )
    op.create_table(
        "registrations",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("exam_offering_id", sa.Uuid(), nullable=False),
        sa.Column("selected_pricing_plan_id", sa.Uuid(), nullable=True),
        sa.Column("form_definition_id", sa.Uuid(), nullable=True),
        sa.Column("form_definition_version", sa.Integer(), nullable=True),
        sa.Column("draft_token_hash", sa.String(length=64), nullable=False),
        sa.Column("draft_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("gender", sa.String(length=16), nullable=True),
        sa.Column("national_code", sa.String(length=10), nullable=True),
        sa.Column("father_name", sa.String(length=200), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("home_phone", sa.String(length=32), nullable=True),
        sa.Column("current_school_id", sa.Uuid(), nullable=True),
        sa.Column("previous_school_id", sa.Uuid(), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("profile_image_id", sa.Uuid(), nullable=True),
        sa.Column("extra_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payable_amount", sa.Integer(), nullable=True),
        sa.Column("payable_currency", sa.String(length=8), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payment_status", sa.String(length=16), nullable=False),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gender IS NULL OR gender IN ('FEMALE', 'MALE', 'OTHER')",
            name=op.f("ck_registrations_valid_gender"),
        ),
        sa.CheckConstraint(
            "payment_status IN ('PENDING', 'SUCCESSFUL', 'FAILED')",
            name=op.f("ck_registrations_valid_payment_status"),
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PHONE_VERIFICATION_REQUIRED', 'PHONE_VERIFIED', 'READY_FOR_SUBMISSION', 'SUBMITTED', 'PAYMENT_PENDING', 'COMPLETED', 'CANCELLED')",
            name=op.f("ck_registrations_valid_status"),
        ),
        sa.CheckConstraint(
            "payable_amount IS NULL OR payable_amount >= 0",
            name=op.f("ck_registrations_payable_amount_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["current_school_id"],
            ["school_directory_entries.id"],
            name=op.f("fk_registrations_current_school_id_school_directory_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_school_id"],
            ["school_directory_entries.id"],
            name=op.f("fk_registrations_previous_school_id_school_directory_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "exam_offering_id"],
            ["exam_offerings.tenant_id", "exam_offerings.id"],
            name=op.f("fk_registrations_tenant_id_exam_offering_id_exam_offerings"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "form_definition_id"],
            ["registration_form_definitions.tenant_id", "registration_form_definitions.id"],
            name=op.f(
                "fk_registrations_tenant_id_form_definition_id_registration_form_definitions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "profile_image_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_registrations_tenant_id_profile_image_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "selected_pricing_plan_id"],
            ["pricing_plans.tenant_id", "pricing_plans.id"],
            name=op.f("fk_registrations_tenant_id_selected_pricing_plan_id_pricing_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_registrations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
        sa.UniqueConstraint(
            "tenant_id",
            "exam_offering_id",
            "national_code",
            name=op.f("uq_registrations_tenant_id_exam_offering_id_national_code"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_registrations_tenant_id_id")),
    )
    op.create_index(
        "ix_registrations_tenant_phone",
        "registrations",
        ["tenant_id", "phone_number"],
        unique=False,
    )
    op.create_index(
        "ix_registrations_tenant_status_created",
        "registrations",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "sample_exams",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("education_level", sa.String(length=100), nullable=True),
        sa.Column("exam_year", sa.Integer(), nullable=True),
        sa.Column("file_media_id", sa.Uuid(), nullable=False),
        sa.Column("cover_media_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')",
            name=op.f("ck_sample_exams_valid_status"),
        ),
        sa.CheckConstraint(
            "download_count >= 0", name=op.f("ck_sample_exams_download_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "cover_media_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_sample_exams_tenant_id_cover_media_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "file_media_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_sample_exams_tenant_id_file_media_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sample_exams_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sample_exams")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sample_exams_tenant_id_id")),
    )
    op.create_index(
        "ix_sample_exams_tenant_public",
        "sample_exams",
        ["tenant_id", "status", "sort_order"],
        unique=False,
    )
    op.create_table(
        "staff_members",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("member_type", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("biography", sa.Text(), nullable=True),
        sa.Column("image_id", sa.Uuid(), nullable=True),
        sa.Column("public_phone", sa.String(length=32), nullable=True),
        sa.Column("public_email", sa.String(length=320), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "member_type IN ('TEACHER', 'EMPLOYEE', 'MANAGER', 'OTHER')",
            name=op.f("ck_staff_members_valid_type"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "image_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_staff_members_tenant_id_image_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_staff_members_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff_members")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_staff_members_tenant_id_id")),
    )
    op.create_index(
        "ix_staff_members_tenant_active",
        "staff_members",
        ["tenant_id", "is_active", "sort_order"],
        unique=False,
    )
    op.create_table(
        "gallery_items",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("album_id", sa.Uuid(), nullable=False),
        sa.Column("media_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "album_id"],
            ["gallery_albums.tenant_id", "gallery_albums.id"],
            name=op.f("fk_gallery_items_tenant_id_album_id_gallery_albums"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "media_id"],
            ["media_assets.tenant_id", "media_assets.id"],
            name=op.f("fk_gallery_items_tenant_id_media_id_media_assets"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_gallery_items_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gallery_items")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_gallery_items_tenant_id_id")),
    )
    op.create_index(
        "ix_gallery_items_tenant_album_order",
        "gallery_items",
        ["tenant_id", "album_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "otp_challenges",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=False),
        sa.Column("code_hash", sa.String(length=256), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("request_ip_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_otp_challenges_attempt_count_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "registration_id"],
            ["registrations.tenant_id", "registrations.id"],
            name=op.f("fk_otp_challenges_tenant_id_registration_id_registrations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_otp_challenges_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_challenges")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_otp_challenges_tenant_id_id")),
    )
    op.create_index(
        "ix_otp_challenges_ip_created",
        "otp_challenges",
        ["request_ip_hash", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_otp_challenges_tenant_phone_created",
        "otp_challenges",
        ["tenant_id", "phone_number", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_otp_challenges_tenant_registration_created",
        "otp_challenges",
        ["tenant_id", "registration_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "payment_transactions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider_authority", sa.String(length=255), nullable=True),
        sa.Column("provider_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("callback_nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("callback_state", sa.Text(), nullable=False),
        sa.Column("callback_consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('INITIATED', 'PENDING', 'SUCCESSFUL', 'FAILED', 'CANCELLED', 'REFUNDED')",
            name=op.f("ck_payment_transactions_valid_status"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_payment_transactions_amount_nonnegative")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "registration_id"],
            ["registrations.tenant_id", "registrations.id"],
            name=op.f("fk_payment_transactions_tenant_id_registration_id_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_payment_transactions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_transactions")),
        sa.UniqueConstraint(
            "provider",
            "provider_transaction_id",
            name=op.f("uq_payment_transactions_provider_provider_transaction_id"),
        ),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payment_transactions_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "idempotency_key",
            name=op.f("uq_payment_transactions_tenant_id_idempotency_key"),
        ),
    )
    op.create_index(
        "ix_payment_transactions_tenant_registration",
        "payment_transactions",
        ["tenant_id", "registration_id"],
        unique=False,
    )
    op.create_index(
        "ix_payment_transactions_tenant_status_created",
        "payment_transactions",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_payment_transactions_active_registration",
        "payment_transactions",
        ["tenant_id", "registration_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('INITIATED', 'PENDING')"),
    )
    op.create_table(
        "registration_contacts",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("registration_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone_number", sa.String(length=16), nullable=False),
        sa.Column("relationship", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position IN (1, 2)", name=op.f("ck_registration_contacts_valid_position")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "registration_id"],
            ["registrations.tenant_id", "registrations.id"],
            name=op.f("fk_registration_contacts_tenant_id_registration_id_registrations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_registration_contacts_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_contacts")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_registration_contacts_tenant_id_id")),
        sa.UniqueConstraint(
            "tenant_id",
            "registration_id",
            "position",
            name=op.f("uq_registration_contacts_tenant_id_registration_id_position"),
        ),
    )
    op.create_index(
        "ix_registration_contacts_tenant_registration",
        "registration_contacts",
        ["tenant_id", "registration_id"],
        unique=False,
    )
    tenant_tables = (
        "audit_events",
        "banners",
        "contact_requests",
        "exam_offerings",
        "exam_pricing_plans",
        "gallery_albums",
        "gallery_items",
        "honor_categories",
        "honors",
        "media_assets",
        "otp_challenges",
        "payment_transactions",
        "posts",
        "pricing_plans",
        "registration_contacts",
        "registration_form_definitions",
        "registrations",
        "sample_exams",
        "staff_members",
        "tenant_addresses",
        "tenant_features",
        "tenant_memberships",
        "tenant_phones",
        "tenant_profiles",
        "tenant_social_links",
    )
    predicate = "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid"
    for table_name in tenant_tables:
        op.execute(sa.text(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY'))
        op.execute(
            sa.text(
                f'CREATE POLICY tenant_isolation ON "{table_name}" '
                f"USING ({predicate}) WITH CHECK ({predicate})"
            )
        )

    # Existing objects are granted explicitly; default privileges are configured by operators
    # for later migrations because they are scoped to the migration owner identity.
    op.execute("GRANT USAGE ON SCHEMA public TO kanoon_app")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kanoon_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_registration_contacts_tenant_registration", table_name="registration_contacts"
    )
    op.drop_table("registration_contacts")
    op.drop_index(
        "ix_payment_transactions_tenant_status_created", table_name="payment_transactions"
    )
    op.drop_index("uq_payment_transactions_active_registration", table_name="payment_transactions")
    op.drop_index("ix_payment_transactions_tenant_registration", table_name="payment_transactions")
    op.drop_table("payment_transactions")
    op.drop_index("ix_otp_challenges_tenant_registration_created", table_name="otp_challenges")
    op.drop_index("ix_otp_challenges_tenant_phone_created", table_name="otp_challenges")
    op.drop_index("ix_otp_challenges_ip_created", table_name="otp_challenges")
    op.drop_table("otp_challenges")
    op.drop_index("ix_gallery_items_tenant_album_order", table_name="gallery_items")
    op.drop_table("gallery_items")
    op.drop_index("ix_staff_members_tenant_active", table_name="staff_members")
    op.drop_table("staff_members")
    op.drop_index("ix_sample_exams_tenant_public", table_name="sample_exams")
    op.drop_table("sample_exams")
    op.drop_index("ix_registrations_tenant_status_created", table_name="registrations")
    op.drop_index("ix_registrations_tenant_phone", table_name="registrations")
    op.drop_table("registrations")
    op.drop_index("ix_posts_tenant_kind_public", table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_honors_tenant_public", table_name="honors")
    op.drop_table("honors")
    op.drop_index("ix_gallery_albums_tenant_public", table_name="gallery_albums")
    op.drop_table("gallery_albums")
    op.drop_table("exam_pricing_plans")
    op.drop_index("ix_banners_tenant_public", table_name="banners")
    op.drop_table("banners")
    op.drop_table("tenant_social_links")
    op.drop_table("tenant_profiles")
    op.drop_table("tenant_phones")
    op.drop_index("ix_tenant_memberships_tenant_role", table_name="tenant_memberships")
    op.drop_table("tenant_memberships")
    op.drop_index("ix_tenant_features_tenant_enabled", table_name="tenant_features")
    op.drop_table("tenant_features")
    op.drop_index(op.f("ix_tenant_domains_tenant_id"), table_name="tenant_domains")
    op.drop_table("tenant_domains")
    op.drop_table("tenant_addresses")
    op.drop_table("registration_form_definitions")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_pricing_plans_tenant_public", table_name="pricing_plans")
    op.drop_table("pricing_plans")
    op.drop_index("ix_media_assets_tenant_created", table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_table("honor_categories")
    op.drop_index("ix_exam_offerings_tenant_public", table_name="exam_offerings")
    op.drop_table("exam_offerings")
    op.drop_index("ix_contact_requests_tenant_phone_created", table_name="contact_requests")
    op.drop_index("ix_contact_requests_tenant_ip_created", table_name="contact_requests")
    op.drop_index("ix_contact_requests_tenant_status_created", table_name="contact_requests")
    op.drop_table("contact_requests")
    op.drop_index("ix_audit_events_tenant_entity", table_name="audit_events")
    op.drop_index("ix_audit_events_tenant_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("users")
    op.drop_table("tenants")
    op.drop_table("school_directory_entries")
    op.drop_index("ix_auth_attempt_scope_created", table_name="authentication_attempts")
    op.drop_table("authentication_attempts")
    # ### end Alembic commands ###
